language: python
cache: pip
sudo: false

# Test environments
matrix:
  include:
   - env: TOXENV=py36-django1.11
     python: 3.6
   - env: TOXENV=py36-django2.0
     python: 3.6
   - env: TOXENV=flake8
     python: 3.6

# Package installation
install:
  - pip install tox codecov

# Run tests
script:
  tox

# Register code coverage
after_success:
  codecov