# Generated by Django 2.0 on 2018-04-23 01:35

import django.core.validators
from django.db import migrations, models
import ej_conversations.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(help_text='Body of text for the comment', max_length=140, validators=[django.core.validators.MinLengthValidator(2), ej_conversations.validators.is_not_empty], verbose_name='Content'),
        ),
    ]
