# Generated by Django 2.0 on 2018-05-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_conversations', '0002_comment_is_promoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stereotype',
            name='conversations',
        ),
        migrations.RemoveField(
            model_name='stereotypevote',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='stereotypevote',
            name='stereotype',
        ),
        migrations.AlterField(
            model_name='limits',
            name='max_comments_in_interval',
            field=models.IntegerField(default=1, help_text='Users can post at most this number of comments in the reference interval.', verbose_name='Maximum number of comments'),
        ),
        migrations.AlterField(
            model_name='limits',
            name='max_comments_per_conversation',
            field=models.IntegerField(default=2, help_text='Limit the number of comments in a single conversation.', verbose_name='Maximum number of comments (global)'),
        ),
        migrations.DeleteModel(
            name='Stereotype',
        ),
        migrations.DeleteModel(
            name='StereotypeVote',
        ),
    ]
